apiVersion: v1
kind: Service
metadata:
  name: games-admin
spec:
  ports:
    - name: http-api
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-metrics
      protocol: TCP
      port: 9502
      targetPort: 9502
  selector:
    app: games-admin