apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    qcloud-app: games-admin-hpa
  name: games-admin-hpa
spec:
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: games-admin