apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-admin
spec:
  template:
    spec:
      containers:
        - name: games-admin
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 512Mi
