apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deployments/api.yaml
  - ./services/api.yaml
  - ./configMaps/env.yaml

commonAnnotations:
  owner: base
  project: games-admin
  repo: https://syngit.txxcd.com/niki/games-admin.git
  updatedBy: kustomize
images:
- name: syngit.txxcd.com:4567/niki/games-admin
  newName: syngit.txxcd.com:4567/niki/games-admin
  newTag: latest
