version: '3.6'  # 指定一个明确的版本号
networks:
  swy_network:
      driver: bridge  # 让 Docker 自动创建 bridge 网络
services:
  swy-admin:
    image: ${SWY_DEBUG_IMAGE_PHP_8_1}
    container_name: ${SWY_ADMIN_NAME}
    environment:
      - "TIMEZONE=Asia/Shanghai"
      - "APP_SYSTEM_ENV=docker"
      - "APP_ENV=local"
      - "APP_NAME=${SWY_ADMIN_NAME}"
      - "EXEC_CMD=rm -fr ./runtime/*"
      - "SWY_ADMIN_DOMAIN_NAME=${SWY_ADMIN_DOMAIN_NAME}"
    env_file:
      - ../.env
    working_dir: "/var/www/html"
    extra_hosts:
      - host.docker.internal:${LOCAL_IP}
    dns:
      - ${SWY_DNS}
    ports:
      - ${SWY_ADMIN_PORT}:80
      - ${SWY_ADMIN_WS_PORT}:9502
    volumes:
      - ${SWY_SERVICE_CODE}/${SWY_ADMIN_NAME}:/var/www/html
    entrypoint: ["php", "watch", "-c"]
    networks:
      - swy_network  # 绑定到同一个网络中
  nginx:
      image: nginx:latest
      container_name: nginx_proxy
      environment:
        - "SWY_ADMIN_DOMAIN_NAME=${SWY_ADMIN_DOMAIN_NAME}"  # 使用环境变量配置域名
      ports:
        - "80:80"  # 将宿主机的 80 端口映射到 Nginx 容器的 80 端口
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 你自定义的 Nginx 配置
      depends_on:
        - swy-admin # 依赖于上面的服务
      extra_hosts:
        - host.docker.internal:${LOCAL_IP}
      dns:
        - ${SWY_DNS}
      networks:
        - swy_network