apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-admin
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: tencent-registry-maitang
